# Generated by Django 4.2.7 on 2025-09-01 14:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Source",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                (
                    "type",
                    models.CharField(
                        choices=[("book", "Книга"), ("movie", "Фильм")], max_length=10
                    ),
                ),
            ],
            options={
                "verbose_name": "Источник",
                "verbose_name_plural": "Источники",
                "default_related_name": "source",
            },
        ),
        migrations.CreateModel(
            name="Quote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        max_length=1000, unique=True, verbose_name="Текст"
                    ),
                ),
                (
                    "weight",
                    models.PositiveIntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(
                                1, message="Вес не может быть меньше 1"
                            ),
                            django.core.validators.MaxValueValidator(
                                10, message="Вес не может быть выше 10"
                            ),
                        ],
                        verbose_name="Вес цитаты от 1 до 10",
                    ),
                ),
                (
                    "views",
                    models.PositiveIntegerField(default=1, verbose_name="Просмотры"),
                ),
                ("likes", models.PositiveIntegerField(default=1, verbose_name="Лайки")),
                (
                    "dislikes",
                    models.PositiveIntegerField(default=1, verbose_name="Дизлайки"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="quotes.source",
                        verbose_name="Источник",
                    ),
                ),
            ],
            options={
                "verbose_name": "Цитата",
                "verbose_name_plural": "Цитаты",
                "ordering": ["-created_at"],
                "default_related_name": "quotes",
            },
        ),
    ]
