# Generated by Django 4.2.7 on 2025-09-01 15:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quotes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="source",
            name="name",
            field=models.CharField(
                max_length=255, unique=True, verbose_name="Название"
            ),
        ),
        migrations.AlterField(
            model_name="source",
            name="type",
            field=models.CharField(
                choices=[("book", "Книга"), ("movie", "Фильм")],
                max_length=10,
                verbose_name="Тип источника",
            ),
        ),
    ]
